=== rishi12082005/SEM-3-PRACTICAL-ASSIGNMENTS/XML Practical Assignments/Assignment 2/1.dtd
<!ELEMENT pinfo (roll,name,address,mobile,dob,age,quali)>
	<!ELEMENT roll (#PCDATA)>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT address (#PCDATA)>
	<!ELEMENT mobile (#PCDATA)>
	<!ELEMENT dob (#PCDATA)>
	<!ELEMENT age (#PCDATA)>
	<!ELEMENT quali (#PCDATA)>

=== rishi12082005/SEM-3-PRACTICAL-ASSIGNMENTS/XML Practical Assignments/Assignment 2/1.xml
<?xml version="1.0"?>
	<!DOCTYPE pinfo SYSTEM "1.dtd">
	<pinfo>
		<roll>12</roll>
		<name>Aagan</name>
		<address>$%^TYHUN</address>
		<mobile>7046465749</mobile>
		<dob>040306</dob>
		<age>18</age>
		<quali>IT</quali>
	</pinfo>
