=== rishi12082005/SEM-3-PRACTICAL-ASSIGNMENTS/XML Practical Assignments/Assignment 2/4.dtd
<!ELEMENT student (name,personal,result)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT personal (address,bdate,gender,mobile)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT bdate (#PCDATA)>
<!ELEMENT gender (male | female)>
<!ELEMENT male (#PCDATA)>
<!ELEMENT female (#PCDATA)>
<!ELEMENT mobile (#PCDATA)>
<!ELEMENT result (total,perc,grade)>
<!ELEMENT total (#PCDATA)>
<!ELEMENT perc (#PCDATA)>
<!ELEMENT grade (Pass | First | Dist | Second | Fail)>
<!ELEMENT Pass (#PCDATA)>
<!ELEMENT First (#PCDATA)>
<!ELEMENT Dist (#PCDATA)>
<!ELEMENT Second (#PCDATA)>
<!ELEMENT Fail (#PCDATA)>

=== rishi12082005/SEM-3-PRACTICAL-ASSIGNMENTS/XML Practical Assignments/Assignment 2/4.xml
<?xml version="1.0"?>
	<!DOCTYPE student SYSTEM "4.dtd">
	<student>
	<name>aagam</name>
	<personal>
		<address>abc</address>
		<bdate>4</bdate>
		<gender>
			<male>male</male>
		</gender>
		<mobile>7046465749</mobile>
	</personal>
	<result>
		<total>365</total>
		<perc>100</perc>
		<grade>
			<First>First</First>
		</grade>
	</result>
	</student>
