=== rishi12082005/SEM-3-PRACTICAL-ASSIGNMENTS/XML Practical Assignments/Assignment 2/6.dtd
<!ELEMENT student (name,id,plan)>
<!ELEMENT name (fname,lname)>
<!ELEMENT fname (#PCDATA)>
<!ELEMENT lname (#PCDATA)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT plan (courses)>
<!ELEMENT courses (course)>
<!ATTLIST courses year CDATA #REQUIRED>
<!ELEMENT course (names,sname,record)>
<!ELEMENT names (#PCDATA)>
<!ELEMENT sname (#PCDATA)>
<!ELEMENT record (grade, date)>
<!ELEMENT grade (#PCDATA)>
<!ELEMENT date (#PCDATA)>

=== rishi12082005/SEM-3-PRACTICAL-ASSIGNMENTS/XML Practical Assignments/Assignment 2/6.xml
<?xml version="1.0"?>
	<!DOCTYPE student SYSTEM "6.dtd">
	<student>
		<name>
			<fname>aagam</fname>
			<lname>sanghvi</lname>
		</name>
		<id>1234</id>
		<plan>
			<courses year="2024">
				<course>
					<names>Bca</names>
					<sname>bca</sname>
					<record>
						<grade>a</grade>
						<date>02-08</date>
					</record>
				</course>
			</courses>
		</plan>
	</student>
