=== rishi12082005/SEM-3-PRACTICAL-ASSIGNMENTS/XML Practical Assignments/Assignment 2/8.dtd
<!ELEMENT Student (Roll,Name,Marks,Rank)>
<!ELEMENT Roll (#PCDATA)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Marks (XML,J2EE,NS)>
<!ELEMENT XML (#PCDATA)>
<!ELEMENT J2EE (#PCDATA)>
<!ELEMENT NS (#PCDATA)>
<!ELEMENT Rank (#PCDATA)>

=== rishi12082005/SEM-3-PRACTICAL-ASSIGNMENTS/XML Practical Assignments/Assignment 2/8.xml
<?xml version="1.0"?>
	<!DOCTYPE Student SYSTEM "8.dtd">
	<Student>
		<Roll>323</Roll>
		<Name>AAGAM</Name>
		<Marks>
			<XML>xml</XML>
			<J2EE>j2ee</J2EE>
			<NS>ns</NS>
		</Marks>
		<Rank>A++</Rank>
	</Student>
